version: '3.1'

services:
  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
    ports:
      - "7474:7474" # HTTP
      - "7473:7473" # HTTPS
      - "7687:7687" # Bolt
    ulimits:
      nofile:
        soft: 40000
        hard: 40000

volumes:
  neo4j_data:
  neo4j_import:
  neo4j_logs:
  neo4j_plugins:
