version: '3.1'

services:
  neo4j:
    image: neo4j:enterprise
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_unmanaged__extension__classes: "com.neo4j.bloom.server=/bloom"
      NEO4J_dbms_security_procedures_unrestricted: "bloom.*,apoc.*"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
    volumes:
      - neo4j_data:/data
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    ulimits:
      nofile:
        soft: 40000
        hard: 40000

volumes:
  neo4j_data:
  neo4j_import:
  neo4j_logs:
  neo4j_plugins:
  mysql_data:
