{
 "title": "MySQL",
 "time": { "from": "2019-11-01T00:00:00.000Z", "to": "2019-11-30T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "brand",
    "label": "Brand",
    "query": "SELECT dp.brand \nFROM FactSales AS fs\nJOIN DimProducts AS dp ON dp.product_id = fs.product_id\nGROUP BY dp.brand\nORDER BY SUM(fs.quantity) DESC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Sales of ${brand}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "dw",
     "rawSql": "SELECT fs.date, SUM(fs.quantity)\nFROM dw.FactSales AS fs, dw.DimProducts AS dp\nWHERE fs.product_id = dp.product_id AND dp.brand = \"${brand}\"\nGROUP BY fs.date;"
    }
   ]
  },
  {
   "title": "Unique Customers",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "dw",
     "rawSql": "SELECT fs.date, SUM(fs.unique_customers) FROM dw.FactSales AS fs GROUP BY fs.date;"
    }
   ]
  },
  {
   "title": "${brand}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "dw",
     "rawSql": "SELECT dp.product_id, fs.quantity AS \"Units Sold\", fs.unit_price AS \"Unit Price\"\nFROM dw.FactSales AS fs, dw.DimProducts AS dp\nWHERE dp.product_id = fs.product_id AND dp.brand = \"${brand}\"\nORDER BY fs.quantity DESC"
    }
   ]
  },
  {
   "title": "Number of Sales",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "dw",
     "rawSql": "SELECT fs.date, SUM(fs.quantity) FROM dw.FactSales AS fs GROUP BY fs.date;"
    }
   ]
  },
  {
   "title": "Sales  Per Brand",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "dw",
     "rawSql": "SELECT dp.brand, SUM(fs.quantity) AS \"Units Sold\", AVG(fs.unit_price) AS \"Average Unit Price\", COUNT(*) AS \"Number of Products\"\nFROM dw.FactSales AS fs\nJOIN dw.DimProducts AS dp ON dp.product_id = fs.product_id\nGROUP BY dp.brand\nORDER BY SUM(fs.quantity) DESC;"
    }
   ]
  }
 ]
}